config/routes.rb
Beta1::Application.routes.draw do
  get "static_pages/home"
  get "static_pages/whyus"
  get "static_pages/aboutus"
  get "static_pages/profiler"
  get "static_pages/contact"

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def whyus
  end

  def aboutus
  end

  def profiler
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Investify</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="navbar navbar-fixed-top">
  		<div class="navbar-inner">
  			<div class ="container">
  				<a href = "#" class = "brand">Investify</a>
  				<ul class = "nav">
  					<li><%= link_to "Why Investify", static_pages_whyus_path %><li>
  					<li><%= link_to "About Us", static_pages_aboutus_path %><li>	
  					<li><%= link_to "Profiler", static_pages_profiler_path %><li>
  					<li><%= link_to "Contact", static_pages_contact_path %><li>
  			</div>
  		</div>
  	</div>

	<div class="container">	
		<%= yield %>	
	</div>
</body>
</html>

app/views/static_pages/aboutus.html.erb
<h1>StaticPages#aboutus</h1>
<p>Find me in app/views/static_pages/aboutus.html.erb</p>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>

app/views/static_pages/profiler.html.erb
<h1>StaticPages#profiler</h1>
<p>Find me in app/views/static_pages/profiler.html.erb</p>

app/views/static_pages/whyus.html.erb
<h1>StaticPages#whyus</h1>
<p>Find me in app/views/static_pages/whyus.html.erb</p>